#!/bin/sh

set -u
set -e

FONTDIR="../../fonts/"
#FONTDIR="/dev/shm/.vdr/vdr/config/plugins/graphlcd/fonts/"
if [ ! -d "$FONTDIR" ]; then
	echo "Not in skin directory. Exit."
	exit 1
fi

splitfont() {
	OLDIFS=$IFS
	IFS='
'
	for f in $1; do
		echo $(echo "$f" | cut -d ":" -f 1)
		break
	done
	IFS=$OLDIFS
}

printf "Checking for \"Ubuntu Bold\"..."
font="$(fc-list :fullname='Ubuntu Bold' file)"
font=$(splitfont "$font")
if [ -z "$font" ]; then
	printf " fail.\n"
	printf "  \"Ubuntu Bold\" not found\n"
	printf "  Ubuntu User run \"apt-get install ttf-ubuntu-font-family\"\n"
	printf "  on other Systems go to \"http://font.ubuntu.com/\"\n"
	exit 1
else
	printf " pass.\n"
	printf "  found at \"$font\"\n"
fi
if [ ! -e "${FONTDIR}Ubuntu-B.ttf" ]; then
	printf "  linking \"${FONTDIR}Ubuntu-B.ttf\" to \"$font\"\n"
	ln -s "$font" "${FONTDIR}Ubuntu-B.ttf"
fi

printf "Checking for \"Ubuntu Mono Bold\"..."
font="$(fc-list :fullname='Ubuntu Mono Bold' file)"
font=$(splitfont "$font")
if [ -z "$font" ]; then
	printf " fail.\n"
	printf "  \"Ubuntu Mono Bold\" not found\n"
	printf "  Ubuntu User run \"apt-get install ttf-ubuntu-font-family\"\n"
	printf "  on other Systems go to \"http://font.ubuntu.com/\"\n"
	exit 1
else
	printf " pass.\n"
	printf "  found at \"$font\"\n"
fi
if [ ! -e "${FONTDIR}UbuntuMono-B.ttf" ]; then
	printf "  linking \"${FONTDIR}UbuntuMono-B.ttf\" to \"$font\"\n"
	ln -s "$font" "${FONTDIR}UbuntuMono-B.ttf"
fi

printf "Checking for \"Ubuntu Condensed\"..."
font="$(fc-list :fullname='Ubuntu Condensed' file)"
font=$(splitfont "$font")
if [ -z "$font" ]; then
	printf " fail.\n"
	printf "  \"Ubuntu Condensed\" not found\n"
	printf "  Ubuntu User run \"apt-get install ttf-ubuntu-font-family\"\n"
	printf "  on other Systems go to \"http://font.ubuntu.com/\"\n"
	exit 1
else
	printf " pass.\n"
	printf "  found at \"$font\"\n"
fi
if [ ! -e "${FONTDIR}Ubuntu-C.ttf" ]; then
	printf "  linking \"${FONTDIR}Ubuntu-C.ttf\" to \"$font\"\n"
	ln -s "$font" "${FONTDIR}Ubuntu-C.ttf"
fi

printf "Checking for \"VDRSymbols Sans\"..."
font="$(fc-list :fullname='VDRSymbols Sans' file)"
font=$(splitfont "$font")
if [ -z "$font" ]; then
	printf " fail.\n"
	printf "  \"VDRSymbols Sans\" not found\n"
	printf "  Debian/Ubuntu Users using a VDR Repository usualliy run \"apt-get install ttf-vdrsymbols\"\n"
	printf "  on other Systems go to \"http://andreas.vdr-developer.org/fonts/download.html\"\n"
	exit 1
else
	printf " pass.\n"
	printf "  found at \"$font\"\n"
fi
if [ ! -e "${FONTDIR}VDRSymbolsSans.ttf" ]; then
	printf "  linking \"${FONTDIR}VDRSymbolsSans.ttf\" to \"$font\"\n"
	ln -s "$font" "${FONTDIR}VDRSymbolsSans.ttf"
fi

printf "Checking for \"VDRSymbols Sans Bold\"..."
font="$(fc-list :fullname='VDRSymbols Sans Bold' file)"
font=$(splitfont "$font")
if [ -z "$font" ]; then
	printf " fail.\n"
	printf "  \"VDRSymbols Sans Bold\" not found\n"
	printf "  Debian/Ubuntu Users using a VDR Repository usualliy run \"apt-get install ttf-vdrsymbols\"\n"
	printf "  on other Systems go to \"http://andreas.vdr-developer.org/fonts/download.html\"\n"
	exit 1
else
	printf " pass.\n"
	printf "  found at \"$font\"\n"
fi
if [ ! -e "${FONTDIR}VDRSymbolsSans-Bold.ttf" ]; then
	printf "  linking \"${FONTDIR}VDRSymbolsSans-Bold.ttf\" to \"$font\"\n"
	ln -s "$font" "${FONTDIR}VDRSymbolsSans-Bold.ttf"
fi

exit 0
