<variable id="Color.Bar.Background.Normal" value="'0x04022C'"/>
<variable id="Color.Bar.Background.Record" value="'0x480000'"/>
<variable id="Color.Bar.Foreground" value="'white'"/>
<variable id="Color.Message.Blank" value="'white'"/>
<variable id="Color.Message.Info" value="'0xFCFE84'"/>
<variable id="Color.Message.Warning" value="'0x68FF66'"/>
<variable id="Color.Message.Error" value="'0xFF60AD'"/>
