<!--
  This ist an XML snipped. The syntax must follow the XML rules.

  Attention: Only change the "value" Entries.
-->



  <variable evaluate="once" id="ColorMenuBackground"
    value="'white'"
  />

  <variable evaluate="once" id="ColorMenuTitle"
    value="'white'"
  />

  <variable evaluate="once" id="ColorMenuItem"
    value="'black'"
  />

  <variable evaluate="once" id="ColorMenuItemCurrent"
    value="'white'"
  />

  <variable evaluate="once" id="ColorMenuText"
    value="'black'"
  />

  <variable evaluate="once" id="ColorMenuButtonRedForeground"
    value="'black'"
  />

  <variable evaluate="once" id="ColorMenuButtonGreenForeground"
    value="'black'"
  />

  <variable evaluate="once" id="ColorMenuButtonYellowForeground"
    value="'black'"
  />

  <variable evaluate="once" id="ColorMenuButtonBlueForeground"
    value="'black'"
  />

  <variable evaluate="once" id="ColorMenuAudioTitle"
    value="'black'"
  />

  <variable evaluate="once" id="ColorMenuAudioItem"
    value="'black'"
  />

  <variable evaluate="once" id="ColorMessageForeground"
    value="'black'"
  />

  <variable evaluate="once" id="ColorChannelNumber"
    value="'black'"
  />

  <variable evaluate="once" id="ColorChannelName"
    value="'black'"
  />

  <variable evaluate="once" id="ColorClockForeground"
    value="'black'"
  />

  <variable evaluate="once" id="ColorBarBackgroundNormal"
    value="'0x04022C'"
  />

  <variable evaluate="once" id="ColorBarBackgroundRecord"
    value="'0x480000'"
  />

  <variable evaluate="once" id="ColorBarForeground"
    value="'white'"
  />

  <variable evaluate="once" id="ColorMessageForegroundTitle"
    value="'black'"
  />

  <variable evaluate="once" id="ColorMessageForegroundOrgin"
    value="'black'"
  />

  <variable evaluate="once" id="ColorMessageForegroundText"
    value="'black'"
  />

  <variable evaluate="once" id="ColorMessageBlank"
    value="'white'"
  />

  <variable evaluate="once" id="ColorMessageInfo"
    value="'0xFCFE84'"
  />

  <variable evaluate="once" id="ColorMessageWarning"
    value="'0x68FF66'"
  />

  <variable evaluate="once" id="ColorMessageError"
    value="'0xFF60AD'"
  />

  <variable evaluate="once" id="ColorAttentionBackground"
    value="'red'"
  />

  <variable evaluate="once" id="ColorAttentionForeground"
    value="'white'"
  />

  <variable evaluate="once" id="ColorDisplayErrorBackground"
    value="{DefaultBackgroundColor}"
  />

  <variable evaluate="once" id="ColorDisplayErrorForeground"
    value="{DefaultForegroundColor}"
  />
